### ISSUE TITLE
Swaps in development failing with obscure error message

### ISSUE THREAD

**Issue by boriskubrik** [sifiorg/sifi#454]
All swaps seem to instantly fail with this error in development. Production works.

@xykota any suggestions?

```
mutation.ts:261 SifiError: Request failed: 
    at _callee7$ (Sifi.ts:155:9)
    at tryCatch (sdk.esm.js:42:17)
    at Generator.<anonymous> (sdk.esm.js:123:22)
    at Generator.next (sdk.esm.js:67:21)
    at asyncGeneratorStep (sdk.esm.js:304:24)
    at _next (sdk.esm.js:323:9)
    at sdk.esm.js:328:7
    at new Promise (<anonymous>)
    at sdk.esm.js:320:12
    at handleResponse (Sifi.ts:138:30)
 ```

![image](https://github.com/sifiorg/sifi/assets/128667801/c852ce57-80d6-4591-ada4-cf582753f275)

**Comment by xykota** [comment]
The key is `handleResponse` in `Sifi.ts:138`:

https://github.com/sifiorg/sifi/blob/e8fd00bd111dd4f3553626c3e15e4c3cddcbcc85/packages/sdk/src/Sifi.ts#L162

Can you look in the network inspector and see what the network error was? The error handling in `handleResponse` is not very good

**Comment by immutablegoblin** [comment]
@xykota 

May be related, not sure yet - but I'm getting

```
{
   "code":"BAD_REQUEST",
   "message":"Input error: quote.source.quote.element.actions.0.dstWarpLinkEngage.gasForCall: Invalid bigint"
}
```

When trying to execute swaps on ETH (mainnet) -> USDC (Arbitrum)

(Prod!)

**Comment by boriskubrik** [comment]
@xykota it seems that the SDK does not return a quote ID _in development_. Works on production.

```
{
  id: undefined,
  toAmount: 9999425n,
  estimatedGas: 315600n,
  approveAddress: "0x65c49E9996A877d062085B71E1460fFBe3C4c5Aa",
  permit2Address: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
  toAmountAfterFeesUsd: "9.93"
}
```

**Comment by xykota** [comment]
> @xykota it seems that the SDK does not return a quote ID _in development_. Works on production.

Quote IDs have been deprecated in favor of sending back the entire quote when getting the swap. This allows the backend to be stateless and even swap tx to be constructed in frontend.

**Comment by xykota** [comment]
> ```
> {
>    "code":"BAD_REQUEST",
>    "message":"Input error: quote.source.quote.element.actions.0.dstWarpLinkEngage.gasForCall: Invalid bigint"
> }
> ```

Thanks for the report, fixed!

**Comment by boriskubrik** [comment]
Turns out I needed to run `pnpm build` to build the latest version of the SDK. 🤦
